# Site
repository: abhical/webresume
favicon: images/favicon.ico

# Personal info
name: Abhishek Pandey
title: Web Developer and Software Quality Assurance Engineer
email: abhi.shivam0930@gmail.com
website: coming soon

# Social links
#twitter_username: facespics
github_username:  abhical
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: abhishek.__.pandey
linkedin_username: abhical
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Abhishek and I'm a Web Developer and Software Quality Assurance Engineer. I am very passionate about building things which solves some genuine problems, a self taught developer who loves to explore new things, 
  I have good understanding of data structure and algorithm, SQL, Software Development and testing. Working in C++ and JAVASCRIPT and have excellent written, communication as well as presentation skills. 
  Experienced at working as a team and learning effectively.
  <br/>
   I am also skilled in: <mark>Crossfit</mark> and <mark>Gymnastic</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering some of my other interests and hobbies are:
   - Crossfit
   - Gymnastic
   - Reading
   - Football

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
