# Site
repository: abhical/webresume
favicon: images/favicon.ico

# Personal info
name: Abhishek Pandey
title: Web Developer and Software Quality Assurance Engineer
email: abhi.shivam0930@gmail.com
website: coming soon

# Social links
#twitter_username: facespics
github_username:  abhical
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: abhishek.__.pandey
linkedin_username: abhical
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Abhishek and I'm a self taught Web Developer and Software Quality Assurance Engineer.I have good understanding of data structure and algorithm, SQL, Software Development, writing great code, designing efficient databases, updating API information and debugging code.
  I have a hands-on experience on Javascript, React.j, RESTful API, HTML, CSS and with project management , UI/UX and development skills my goal is to keep learning and dedicate myself to creating products that make an impact.
  I believe a good software developer takes the commitment of his work and most importantly effective communication to get the results that benefit the business.
  <br/>
   I am also skilled in: <mark>Crossfit</mark> and <mark>Gymnastic</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering some of my other interests and hobbies are:
   - Crossfit
   - Gymnastic
   - Reading
   - Football

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
