# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Abhishek Pandey
title: Web Developer and Software Quality Analsyt
email: abhi.shivam0930@gmail.com
website: coming soon

# Social links
#twitter_username: facespics
github_username:  abhical
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: abhishek.__pandey
linkedin_username: abhishek.__.pandey
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Abhishek and I'm a Web Developer and Software Quality Analyst. I'm proficient at implementing data structures,writing memory efficient code and minimizing run time complexity ,working in C++ and JAVA and have excellent written, communication as well as presentation skills.
Experienced at working as a team and learning effectively. 

  I am most skilled in: <mark>Crossfit</mark> and <mark>Gymnastic</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
